pygments: true
relative_permalinks: false
url: http://ccpaging.github.io/algebra
title: CCPAGING â€¢ Algebra.
description: Algebra self-learning.
google_analytics_id: 
exclude: ["CNAME", "README", "bin", "build.xml"]
permalink: /algebra/news/:year/:month/:day/:title/

author :
  name : ccpaging
  email : ccpaging@gmail.com
  github : ccpaging
  twitter : 

project:
  name: Algebra
  github: algebra

markdown: kramdown
