pygments: true
relative_permalinks: false
url: http://ccpaging.github.io/algebra
title: CCPAGING â€¢ Algebra.
description: Algebra self-learning.
exclude: ["CNAME", "bin", "build.xml"]
permalink: /news/:year-:month-:day-:title/

beian: 
cnzz: 1000283298
baidu: 
google_analytics_id: UA-48436988-1

duoshuo: ccpaging

author :
  name : ccpaging
  email : ccpaging@gmail.com
  github : ccpaging
  twitter : 

project:
  name: Algebra
  github: algebra

markdown: kramdown
